name: cloudflare pages

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v6

      - name: Setup Zine
        uses: kristoff-it/setup-zine@v1

      - name: Build
        run: zine release

      - name: Deploy
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./public --project-name=zigtools-website
          # Optional: Used for adding GitHub deployments support
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
